# Generated by Django 4.1.1 on 2024-10-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airquality',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='soilquality',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='waterquality',
            options={'ordering': ['timestamp']},
        ),
    ]
