# Generated by Django 4.1.1 on 2024-10-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_data', '0002_alter_airquality_options_alter_soilquality_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airquality',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AlterModelOptions(
            name='soilquality',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AlterModelOptions(
            name='waterquality',
            options={'ordering': ['timestamp', 'id']},
        ),
    ]
